ANCHO, ALTO = 700, 500
FPS = 60
TITULO = 'Pygame Window'
GAME_FONT = ''
BACK_COLOR = (255, 0, 212)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (40, 250, 21)
YELLOW = (231, 240, 21)
PLAYER_IMG = 'rocket.png'
ENEMY_IMG = 'ufo.png'
BULLET_IMG = 'bullet.png'
BACKGROUND_IMG = 'galaxy.jpg'
GAMEOVER_IMG ='game_over.png'
YOU_WIN_IMG = 'you_win.png'
GOALD_IMG = 'goald.png'
#BGM = 'src/bgm.mp3'
#FIRE_FX = 'src/laser.mp3'
ROCK_IMG = 'asteroid.png'
